name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Ganti dengan nama branch Anda

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Versi Node.js yang sesuai

    - name: Install dependencies
      run: npm install

    - name: Deploy to GitHub Pages
      run: |
        npm run deploy  # Jika ada skrip untuk deploy, pastikan ini ada di package.json
        # Atau Anda bisa menambahkan langkah untuk meng-copy file statis ke folder yang benar
